[[molecule]]
[molecule.simulation]
name = "water"
method = "HF"
basis_set = "STO-3G"

[molecule.system]
charge = 0
multiplicity = 1
geometry = [
  ["H",  0.8668118,     0.6014357,    -0.0000000],
  ["H", -0.8668118,     0.6014357,    -0.0000000],
  ["O",  0.0000000,    -0.0757918,     0.0000000]
]

[molecule.option]
print_integral = "all"

[[molecule]]
[molecule.simulation]
name = "water_bohr"
method = "HF"
basis_set = "STO-3G"

[molecule.system]
geometry = [
  ["H",  1.638037,  1.136548, -0.000000],
  ["H", -1.638037,  1.136548, -0.000000],
  ["O",  0.000000, -0.143226,  0.000000]
]
charge = 0
multiplicity = 1

[molecule.option]
print_integral = "all"
